# Generated by Django 3.0.2 on 2020-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=60)),
                ('price', models.BooleanField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=60)),
            ],
        ),
    ]
