# Generated by Django 3.0.2 on 2020-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phones',
            name='description',
            field=models.TextField(),
        ),
    ]
