# Generated by Django 3.0.2 on 2020-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_phones_phonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
